title: When data are meanings
description: >- 
  Adaptation of algorithms to data that consists of meaningful sentences is a new class of problems, that should be fully understood as such.

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
